-- PostgreSQL schema for Employee Performance Measurement (EPM)
-- Database: masarat_epm
-- Usage:
--   createdb masarat_epm
--   psql -d masarat_epm -f database/20260611_epm_postgresql_schema.sql

CREATE TABLE IF NOT EXISTS "PerformanceCharters" (
    "CharterId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmployeeId" integer NOT NULL,
    "EmployeeNationalId" varchar(10) NOT NULL,
    "EmployeeName" varchar(200) NOT NULL,
    "JobTitle" varchar(200),
    "JobNumber" varchar(50),
    "AgencyName" varchar(200),
    "DepartmentName" varchar(200),
    "JobCategory" varchar(50) NOT NULL DEFAULT 'nonSupervisory',
    "ManagerId" integer NOT NULL,
    "ManagerName" varchar(200) NOT NULL,
    "FiscalYear" integer NOT NULL,
    "Status" varchar(50) NOT NULL DEFAULT 'Draft',
    "EmployeeSignedDate" timestamp without time zone,
    "ManagerApprovedDate" timestamp without time zone,
    "MidYearReviewDate" timestamp without time zone,
    "MidYearReviewNotes" varchar(2000),
    "FinalEvaluationDate" timestamp without time zone,
    "GoalsScore" numeric(5,2),
    "CompetenciesScore" numeric(5,2),
    "TotalScore" numeric(5,2),
    "FinalRating" varchar(50),
    "FinalEvaluationNotes" varchar(2000),
    "HasAppeal" boolean NOT NULL DEFAULT false,
    "AppealDate" timestamp without time zone,
    "AppealNotes" varchar(2000),
    "AppealStatus" varchar(50),
    "ManagerComments" varchar(2000),
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "TenantId" bigint NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedBy" text,
    "UpdatedAt" timestamp without time zone,
    "UpdatedBy" text
);

CREATE TABLE IF NOT EXISTS "Goals" (
    "GoalId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CharterId" integer NOT NULL REFERENCES "PerformanceCharters"("CharterId") ON DELETE CASCADE,
    "OrderIndex" integer NOT NULL,
    "Title" varchar(500) NOT NULL,
    "Description" varchar(2000),
    "Weight" numeric(5,2) NOT NULL,
    "MeasurableIndicators" varchar(1000),
    "TimeFrame" varchar(200),
    "Status" varchar(50) NOT NULL DEFAULT 'Pending',
    "CompletionPercentage" numeric(5,2) NOT NULL DEFAULT 0,
    "ActualScore" numeric(5,2),
    "WeightedScore" numeric(5,2),
    "EvaluationNotes" varchar(2000),
    "EvaluatedDate" timestamp without time zone,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "TenantId" bigint NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedBy" text,
    "UpdatedAt" timestamp without time zone,
    "UpdatedBy" text
);

CREATE TABLE IF NOT EXISTS "Competencies" (
    "CompetencyId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CharterId" integer NOT NULL REFERENCES "PerformanceCharters"("CharterId") ON DELETE CASCADE,
    "CompetencyType" varchar(100) NOT NULL,
    "NameAr" varchar(200) NOT NULL,
    "NameEn" varchar(200),
    "Description" varchar(2000),
    "Weight" numeric(5,2) NOT NULL,
    "Rating" integer,
    "ScorePercentage" numeric(5,2),
    "WeightedScore" numeric(5,2),
    "EvaluationNotes" varchar(2000),
    "PositiveBehaviors" varchar(1000),
    "AreasForImprovement" varchar(1000),
    "EvaluatedDate" timestamp without time zone,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "TenantId" bigint NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedBy" text,
    "UpdatedAt" timestamp without time zone,
    "UpdatedBy" text
);

CREATE TABLE IF NOT EXISTS "ExcellenceElements" (
    "ElementId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CharterId" integer NOT NULL REFERENCES "PerformanceCharters"("CharterId") ON DELETE CASCADE,
    "ElementType" varchar(100) NOT NULL,
    "Title" varchar(500) NOT NULL,
    "Description" varchar(2000),
    "ActivityDate" timestamp without time zone NOT NULL,
    "Impact" varchar(1000),
    "SupportingDocuments" varchar(500),
    "ApprovalStatus" varchar(50) NOT NULL DEFAULT 'Pending',
    "ApprovedDate" timestamp without time zone,
    "ManagerNotes" varchar(1000),
    "BonusPoints" numeric(4,2),
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "TenantId" bigint NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedBy" text,
    "UpdatedAt" timestamp without time zone,
    "UpdatedBy" text
);

CREATE TABLE IF NOT EXISTS "EmployeeSnapshots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceEmployeeId" integer NOT NULL,
    "EmployeeNumber" varchar(50),
    "NationalId" varchar(20) NOT NULL,
    "NameAr" varchar(200) NOT NULL,
    "NameEn" varchar(200),
    "Email" varchar(200),
    "PhoneNumber" varchar(50),
    "DepartmentId" integer,
    "DepartmentName" varchar(200),
    "PositionId" integer,
    "JobTitle" varchar(200),
    "ManagerEmployeeId" integer,
    "ManagerName" varchar(200),
    "EmploymentStatus" varchar(50) NOT NULL DEFAULT 'Active',
    "SourceSystem" varchar(100) NOT NULL DEFAULT 'HR',
    "SourceVersion" varchar(100),
    "LastSyncedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "TenantId" bigint NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "IntegrationSyncLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IntegrationName" varchar(100) NOT NULL,
    "Status" varchar(50) NOT NULL DEFAULT 'Started',
    "PulledCount" integer NOT NULL DEFAULT 0,
    "InsertedCount" integer NOT NULL DEFAULT 0,
    "UpdatedCount" integer NOT NULL DEFAULT 0,
    "FailedCount" integer NOT NULL DEFAULT 0,
    "ErrorMessage" varchar(2000),
    "StartedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CompletedAt" timestamp without time zone,
    "TenantId" bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Charter_Tenant_Employee_Year"
    ON "PerformanceCharters" ("TenantId", "EmployeeId", "FiscalYear");
CREATE INDEX IF NOT EXISTS "IX_Charter_Manager" ON "PerformanceCharters" ("ManagerId");
CREATE INDEX IF NOT EXISTS "IX_Charter_FiscalYear" ON "PerformanceCharters" ("FiscalYear");
CREATE INDEX IF NOT EXISTS "IX_Charter_Status" ON "PerformanceCharters" ("Status");
CREATE INDEX IF NOT EXISTS "IX_PerformanceCharters_TenantId" ON "PerformanceCharters" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_Goal_Charter" ON "Goals" ("CharterId");
CREATE INDEX IF NOT EXISTS "IX_Goal_Charter_Order" ON "Goals" ("CharterId", "OrderIndex");
CREATE INDEX IF NOT EXISTS "IX_Goals_TenantId" ON "Goals" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_Competency_Charter" ON "Competencies" ("CharterId");
CREATE INDEX IF NOT EXISTS "IX_Competency_Type" ON "Competencies" ("CompetencyType");
CREATE INDEX IF NOT EXISTS "IX_Competencies_TenantId" ON "Competencies" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_Excellence_Charter" ON "ExcellenceElements" ("CharterId");
CREATE INDEX IF NOT EXISTS "IX_Excellence_Type" ON "ExcellenceElements" ("ElementType");
CREATE INDEX IF NOT EXISTS "IX_Excellence_Status" ON "ExcellenceElements" ("ApprovalStatus");
CREATE INDEX IF NOT EXISTS "IX_ExcellenceElements_TenantId" ON "ExcellenceElements" ("TenantId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_EmployeeSnapshot_Tenant_Source_Employee"
    ON "EmployeeSnapshots" ("TenantId", "SourceSystem", "SourceEmployeeId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSnapshot_Tenant_NationalId"
    ON "EmployeeSnapshots" ("TenantId", "NationalId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSnapshot_Department" ON "EmployeeSnapshots" ("DepartmentId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSnapshot_Manager" ON "EmployeeSnapshots" ("ManagerEmployeeId");
CREATE INDEX IF NOT EXISTS "IX_EmployeeSnapshots_TenantId" ON "EmployeeSnapshots" ("TenantId");

CREATE INDEX IF NOT EXISTS "IX_IntegrationSyncLog_Tenant_Name_StartedAt"
    ON "IntegrationSyncLogs" ("TenantId", "IntegrationName", "StartedAt");
CREATE INDEX IF NOT EXISTS "IX_IntegrationSyncLogs_TenantId" ON "IntegrationSyncLogs" ("TenantId");
